server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Flutter routing (MUY IMPORTANTE)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # cache assets
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public";
    }

    location /icons/ {
        expires 1y;
        add_header Cache-Control "public";
    }

    # compresión
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}