name: invitacion_boda
description: Proyecto de invitación de boda - Flutter Web (ejemplo)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.10
  carousel_slider: ^4.2.1
  google_fonts: ^4.0.3
  audioplayers: ^3.0.1
  firebase_core: ^2.15.1
  cloud_firestore: ^4.8.4
  card_swiper: ^3.0.1
  infinite_carousel: ^1.0.0
  smooth_page_indicator: ^1.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  universal_html: ^2.2.4
  video_player: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/fondo1.jpg
    - lib/assets/qrphotos.jpeg
    - lib/assets/hombres.png
    - lib/assets/mujeres.png
    - lib/assets/flores.png
    - lib/assets/anillos.png
    - lib/assets/copas.png
    - lib/assets/noniños.gif
    - lib/assets/audio/Fonseca.mp3
    - lib/assets/video/invitacion.mp4
